version: '3.8'
services:
  neo4j:
    image: neo4j:ubi9
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - data:/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.15.3
    ports:
      - '6333:6333'
    volumes:
      - ./qdrant_storage:/qdrant/storage 
    restart: unless-stopped

volumes:
  data:
